spring:
  datasource:
    url: jdbc:h2:mem:testdb  # Banco de dados em memória
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # Habilita o console H2
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update  # Atualiza o esquema do banco de dados automaticamente
    show-sql: true  # Mostra as consultas SQL no console
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
